INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES ( 4 , 1, 10);

INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES ( 5 , 1, 2);

INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES ( 6 , 1, 4);


INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES ( 4 , 2, 2);


INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES ( 5 , 2, 20);


INSERT INTO STOCK(PRODUCT_ID, LOCATION_ID, QUANTITY)
VALUES ( 6 , 2, 30);
