CREATE TABLE IF NOT EXISTS Product(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255),
PRICE DOUBLE,
WEIGHT DOUBLE,
IMAGE_URL VARCHAR(255),
PRODUCT_CATEGORY_ID INT,
CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCTCATEGORY(ID),
SUPPLIER_ID INT,
CONSTRAINT FK_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID));
