CREATE TABLE IF NOT EXISTS Location(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
ADDRESS_COUNTRY VARCHAR(255),
ADDRESS_CITY VARCHAR(255),
ADDRESS_COUNTY VARCHAR(255),
ADDRESS_STREET VARCHAR(255)
);
