CREATE TABLE IF NOT EXISTS PlacedOrder(
ID INT PRIMARY KEY AUTO_INCREMENT,
SHIPPED_FROM_ID INT,
CONSTRAINT FK_SHIPPED_FROM FOREIGN KEY (SHIPPED_FROM_ID) REFERENCES LOCATION(ID),
CUSTOMER_ID INT,
CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
CREATED_AT DATETIME,
ADDRESS_COUNTRY VARCHAR(255),
ADDRESS_CITY VARCHAR(255),
ADDRESS_COUNTY VARCHAR(255),
ADDRESS_STREET VARCHAR(255));


