CREATE TABLE IF NOT EXISTS Stock(
ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID INT,
CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
LOCATION_ID INT,
CONSTRAINT FK_LOCATION_STOCK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID),
QUANTITY INT,
CONSTRAINT UNIQUE_STOCK UNIQUE (PRODUCT_ID,LOCATION_ID)
);
