CREATE TABLE IF NOT EXISTS OrderDetail(
ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID INT,
CONSTRAINT FK_PRODUCT_ORDER_DETAIL FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
ORDER_ID INT,
CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PLACEDORDER(ID),
QUANTITY INT,
CONSTRAINT UNIQUE_ORDER_DETAIL UNIQUE (PRODUCT_ID,ORDER_ID)
);
